FROM heartexlabs/label-studio:latest

# change to root user to create a new user
USER root

RUN addgroup -g 1005 -S labelstudio \
 && adduser -D -u 1004 ops-admin \
 && addgroup ops-admin labelstudio

USER ops-admin
